# Generated by Django 5.2.15 on 2026-07-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_video_3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('living_room', 'Salon'), ('bedroom', 'Chambre'), ('kitchen', 'Cuisine'), ('bathroom', 'Salle de bain'), ('office', 'Bureau'), ('dining', 'Salle à manger'), ('outdoor', 'Extérieur')], max_length=20)),
                ('model_file', models.FileField(help_text='GLB/GLTF 3D model file', upload_to='ar_furniture/models/')),
                ('thumbnail', models.ImageField(upload_to='ar_furniture/thumbnails/')),
                ('width', models.DecimalField(decimal_places=2, help_text='Largeur en mètres', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Hauteur en mètres', max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Profondeur en mètres', max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de référence', max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='ar_furnitur_categor_76e27a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ARConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_width', models.DecimalField(blank=True, decimal_places=2, help_text='Largeur de la pièce en mètres', max_digits=5, null=True)),
                ('room_length', models.DecimalField(blank=True, decimal_places=2, help_text='Longueur de la pièce en mètres', max_digits=5, null=True)),
                ('room_height', models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur de la pièce en mètres', max_digits=5, null=True)),
                ('enable_ar', models.BooleanField(default=True, help_text='Activer la visualisation AR pour cette propriété')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_config', to='properties.property')),
                ('recommended_furniture', models.ManyToManyField(blank=True, related_name='recommended_for', to='ar_furniture.furnituremodel')),
            ],
        ),
    ]
