# Generated by Django 5.2.15 on 2026-07-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_video_3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_date', models.DateField()),
                ('condition', models.CharField(blank=True, help_text='État du bien', max_length=50)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source de la donnée', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['city', 'neighborhood', 'sale_date'], name='price_analy_city_bb5ae3_idx'), models.Index(fields=['property_type', 'transaction_type'], name='price_analy_propert_bc3f1c_idx'), models.Index(fields=['surface_area'], name='price_analy_surface_a7392a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_min_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_max_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_avg_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_difference_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_priced_fairly', models.BooleanField(default=True)),
                ('comparable_sales_count', models.PositiveIntegerField(default=0)),
                ('comparable_sales_ids', models.JSONField(blank=True, default=list)),
                ('market_position', models.CharField(choices=[('below_market', 'En dessous du marché'), ('at_market', 'Dans la moyenne'), ('above_market', 'Au-dessus du marché')], default='at_market', max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_estimation', to='properties.property')),
            ],
            options={
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['property', 'analysis_date'], name='price_analy_propert_69e305_idx'), models.Index(fields=['market_position'], name='price_analy_market__c4e07f_idx')],
            },
        ),
    ]
