# Generated by Django 5.2.15 on 2026-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicPriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('avg_price_per_sqm', models.DecimalField(decimal_places=2, help_text='Average price per m²', max_digits=12)),
                ('min_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_trend', models.CharField(choices=[('rising', 'En hausse'), ('stable', 'Stable'), ('falling', 'En baisse')], default='stable', max_length=20)),
                ('price_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('avg_days_on_market', models.PositiveIntegerField(default=0)),
                ('analysis_period_start', models.DateField()),
                ('analysis_period_end', models.DateField()),
                ('data_points_count', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['city', 'neighborhood'], name='price_analy_city_c83336_idx'), models.Index(fields=['price_trend'], name='price_analy_price_t_f62fb5_idx')],
                'unique_together': {('city', 'neighborhood')},
            },
        ),
    ]
