# Generated by Django 6.0.6 on 2026-06-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=150)),
                ('license_number', models.CharField(blank=True, max_length=60, verbose_name='N° de licence')),
                ('bio', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=1, default=5.0, help_text='En %', max_digits=4)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('response_time_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(blank=True, related_name='agents', to='agents.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
