# Generated by Django 5.2.15 on 2026-06-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_agency_name_user_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('owner', 'Propriétaire'), ('admin', 'Administrateur')], default='client', max_length=10),
        ),
    ]
