# Generated by Django 5.2.15 on 2026-07-04 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_front', models.ImageField(upload_to='id_documents/front/', verbose_name="Recto de la pièce d'identité")),
                ('id_document_back', models.ImageField(upload_to='id_documents/back/', verbose_name="Verso de la pièce d'identité")),
                ('id_document_type', models.CharField(blank=True, max_length=50, verbose_name="Type de pièce d'identité")),
                ('id_document_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro de la pièce d'identité")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé'), ('resubmission_requested', 'Nouvelle soumission demandée')], default='pending', max_length=30, verbose_name='Statut de la demande')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande de vérification d'identité",
                'verbose_name_plural': "Demandes de vérification d'identité",
                'ordering': ['-submitted_at'],
            },
        ),
    ]
