# Generated by Django 5.2.15 on 2026-07-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_identityverificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationrequest',
            name='n8n_execution_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID d'exécution n8n"),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='n8n_resume_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de reprise n8n'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_publish_properties',
            field=models.BooleanField(default=False, help_text='Autorisé à publier des propriétés après vérification'),
        ),
    ]
