# Generated by Django 5.2.15 on 2026-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identityverificationrequest_n8n_execution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('buyer', 'Acheteur'), ('owner', 'Propriétaire'), ('agent', 'Agent'), ('admin', 'Administrateur')], default='client', max_length=10),
        ),
    ]
