# Generated by Django 5.2.15 on 2026-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accounts_us_role_1fa9a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('owner', 'Propriétaire'), ('admin', 'Administrateur')], default='client', max_length=10),
        ),
    ]
