# Generated by Django 5.2.15 on 2026-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationrequest',
            name='field_visit_agent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agent de visite'),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='field_visit_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de visite effectuée'),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='field_visit_notes',
            field=models.TextField(blank=True, verbose_name='Notes de visite'),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='field_visit_scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de visite programmée'),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='property_verification_notes',
            field=models.TextField(blank=True, verbose_name='Notes de vérification du bien'),
        ),
        migrations.AddField(
            model_name='identityverificationrequest',
            name='property_verified',
            field=models.BooleanField(default=False, verbose_name='Bien vérifié sur place'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_visit_agent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agent de visite'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_visit_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de visite effectuée'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_visit_notes',
            field=models.TextField(blank=True, verbose_name='Notes de visite'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_visit_scheduled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de visite programmée'),
        ),
        migrations.AddField(
            model_name='user',
            name='property_verification_notes',
            field=models.TextField(blank=True, verbose_name='Notes de vérification du bien'),
        ),
        migrations.AddField(
            model_name='user',
            name='property_verified',
            field=models.BooleanField(default=False, verbose_name='Bien vérifié sur place'),
        ),
        migrations.AlterField(
            model_name='identityverificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de documents'), ('documents_under_review', "Documents en cours d'analyse"), ('field_visit_scheduled', 'Vérification terrain programmée'), ('field_visit_completed', 'Vérification terrain effectuée'), ('approved', 'Validé'), ('rejected', 'Refusé'), ('resubmission_requested', 'Nouvelle soumission demandée')], default='pending', max_length=30, verbose_name='Statut de la demande'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Non vérifié'), ('pending_documents', "Documents en cours d'analyse"), ('pending_field_visit', 'Vérification terrain programmée'), ('field_visit_completed', 'Vérification terrain effectuée'), ('approved', 'Identité vérifiée'), ('rejected', 'Identité rejetée')], default='unverified', max_length=30),
        ),
    ]
