# Generated by Django 6.0.6 on 2026-06-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône Heroicons (ex: wifi, fire, sparkles)", max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('penthouse', 'Penthouse'), ('maison_de_ville', 'Maison de ville'), ('commercial', 'Commercial'), ('terrain', 'Terrain'), ('ferme', 'Ferme'), ('cottage', 'Cottage'), ('loft', 'Loft'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('ranch', 'Ranch'), ('mobile_home', 'Mobile Home'), ('copropriete', 'Copropriété'), ('bungalow', 'Bungalow'), ('chateau', 'Château')], default='appartement', max_length=30)),
                ('transaction_type', models.CharField(choices=[('vente', 'À vendre'), ('location', 'À louer')], default='vente', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('country', models.CharField(default='US', max_length=80)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Chambres')),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Salles de bain')),
                ('surface_area', models.DecimalField(decimal_places=2, default=0, help_text='m²', max_digits=10)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu'), ('loue', 'Loué'), ('brouillon', 'Brouillon')], default='disponible', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=True, help_text='Annonce validée par un administrateur')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agents.agent')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
