# Generated by Django 6.0.6 on 2026-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Mandat exclusif DOMIORA'),
        ),
        migrations.AddField(
            model_name='property',
            name='stock_image_urls',
            field=models.JSONField(blank=True, default=list, help_text="Images de démonstration (URLs) utilisées tant qu'aucune photo n'est uploadée"),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text="Lien d'une visite virtuelle (Matterport, vidéo 360°, YouTube...)"),
        ),
    ]
