# Generated by Django 5.2.15 on 2026-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentreview'),
        ('properties', '0002_property_is_exclusive_property_stock_image_urls_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'is_validated', 'status'], name='properties__is_publ_0b6c71_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['transaction_type', 'property_type'], name='properties__transac_ceec60_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
    ]
