# Generated by Django 5.2.15 on 2026-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_agent_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Annonce validée par un administrateur'),
        ),
    ]
