# Generated by Django 5.2.15 on 2026-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_nearby_services_property_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_3d',
            field=models.FileField(blank=True, help_text='Vidéo 3D ou visite virtuelle immersive (MP4, WebM)', null=True, upload_to='properties/3d_videos/', verbose_name='Vidéo 3D/Visite virtuelle'),
        ),
    ]
