# Generated by Django 5.2.15 on 2026-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_video_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de création'), ('done', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_video',
            field=models.FileField(blank=True, null=True, upload_to='properties/generated_tours/'),
        ),
    ]
