# Generated by Django 5.2.15 on 2026-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_video_status_property_virtual_tour_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='video_3d',
        ),
        migrations.AddField(
            model_name='property',
            name='uploaded_tour_video',
            field=models.FileField(blank=True, help_text='Vidéo MP4 filmée par le propriétaire montrant la propriété', null=True, upload_to='properties/uploaded_tours/', verbose_name='Vidéo de visite filmée'),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_video',
            field=models.FileField(blank=True, help_text='Vidéo générée automatiquement à partir des images', null=True, upload_to='properties/generated_tours/'),
        ),
    ]
