# Generated by Django 5.2.15 on 2026-08-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_property_video_3d_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, JPG, PNG, DOC autorisés', upload_to='properties/documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('titre_propriete', 'Titre de propriété'), ('plan', 'Plan/Schéma'), ('certificat_construction', 'Certificat de construction'), ('facture_services', 'Factures services (eau, électricité)'), ('diagnostique', 'Diagnostique/Inspection'), ('contrat_location', 'Contrat de location'), ('autre', 'Autre document')], default='autre', max_length=30)),
                ('title', models.CharField(help_text='Titre du document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Documents',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='properties__slug_4fd4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', '-created_at'], name='properties__owner_i_282fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['validation_status'], name='properties__validat_7c5a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
