# Generated by Django 5.2.17 on 2026-10-06 16:12

import properties.video.storage
from django.db import migrations, models


def reset_stuck_processing(apps, schema_editor):
    """L'ancien statut "processing" n'existe plus : ces biens n'ont jamais été traités (pas de worker)."""
    Property = apps.get_model("properties", "Property")
    Property.objects.filter(video_status="processing").update(video_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_fix_property_document_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_error',
            field=models.CharField(blank=True, help_text="Message affiché au propriétaire en cas d'échec", max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='video_job_id',
            field=models.CharField(blank=True, help_text='Génération en cours : une tâche plus ancienne ne peut pas écraser le résultat', max_length=36),
        ),
        migrations.AddField(
            model_name='property',
            name='video_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progression de la génération (0-100)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='uploaded_tour_video',
            field=models.FileField(blank=True, help_text='Vidéo MP4 filmée par le propriétaire montrant la propriété', null=True, storage=properties.video.storage.video_storage, upload_to='properties/uploaded_tours/', verbose_name='Vidéo de visite filmée'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'Préparation'), ('generating', 'Génération en cours'), ('assembling', 'Assemblage'), ('done', 'Terminé'), ('failed', 'Erreur')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_video',
            field=models.FileField(blank=True, help_text='Vidéo générée automatiquement à partir des images', null=True, storage=properties.video.storage.video_storage, upload_to='properties/generated_tours/'),
        ),
        migrations.RunPython(reset_stuck_processing, migrations.RunPython.noop),
    ]
