# Generated by Django 5.2.15 on 2026-06-29 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_unique_together_and_more'),
        ('properties', '0004_remove_property_agent_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'owner', 'property')},
        ),
    ]
