# Generated by Django 5.2.15 on 2026-07-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_conversation_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Message texte'), ('visit_request', 'Demande de visite'), ('visit_accepted', 'Visite acceptée'), ('visit_refused', 'Visite refusée'), ('visit_proposed', 'Nouvelle date proposée'), ('info', 'Information')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='proposed_date',
            field=models.DateTimeField(blank=True, help_text='Proposed date for visit', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='visit_status',
            field=models.CharField(blank=True, help_text='Status of visit request', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField()),
                ('message', models.TextField(help_text='Additional message from requester')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('proposed', 'Nouvelle date proposée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text="Owner's response message")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='messaging.conversation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
