# Generated by Django 5.2.15 on 2026-07-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_message_type_message_proposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visit_request',
            field=models.ForeignKey(blank=True, help_text='Related visit request if this message is about a visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.visitrequest'),
        ),
    ]
