# Generated by Django 5.2.15 on 2026-07-25 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_visit_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Message texte'), ('visit_request', 'Demande de visite'), ('visit_accepted', 'Visite acceptée'), ('visit_refused', 'Visite refusée'), ('visit_proposed', 'Nouvelle date proposée'), ('rendezvous_request', 'Demande de rendez-vous'), ('rendezvous_accepted', 'Rendez-vous accepté'), ('rendezvous_refused', 'Rendez-vous refusé'), ('rendezvous_proposed', 'Nouvelle date proposée'), ('info', 'Information')], default='text', max_length=25),
        ),
        migrations.AlterField(
            model_name='message',
            name='proposed_date',
            field=models.DateTimeField(blank=True, help_text='Proposed date for visit or rendezvous', null=True),
        ),
        migrations.CreateModel(
            name='RendezvousRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField()),
                ('message', models.TextField(help_text='Additional message from requester')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('proposed', 'Nouvelle date proposée'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text="Owner's response message")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_requests', to='messaging.conversation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_rendezvous_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='rendezvous_request',
            field=models.ForeignKey(blank=True, help_text='Related rendezvous request if this message is about a rendezvous', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.rendezvousrequest'),
        ),
    ]
