# Generated by Django 5.2.15 on 2026-06-24 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_agentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Gratuit, Standard, Professionnel, Premium', max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix mensuel en USD ou FCFA', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='USD, EUR, XOF, etc.', max_length=10)),
                ('max_listings', models.IntegerField(default=5, help_text="Nombre maximum d'annonces. -1 pour illimité.")),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Durée de validité en jours')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Liste des fonctionnalités sous forme de JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='AgentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente de paiement'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='agents.agent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(blank=True, help_text='ex: Stripe, Mobile Money, Virement', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échoué'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.agentsubscription')),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiement',
                'ordering': ['-payment_date'],
            },
        ),
    ]
