# Generated by Django 5.2.15 on 2026-06-24 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Renouvellement automatique'),
        ),
        migrations.AlterField(
            model_name='agentsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='agentsubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='agentsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente de paiement'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_method',
            field=models.CharField(blank=True, help_text='ex: Stripe, Mobile Money, Virement', max_length=50, verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('success', 'Succès'), ('failed', 'Échoué'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Transaction'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', help_text='USD, EUR, XOF, etc.', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Durée de validité en jours', verbose_name='Durée en jours'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Liste des fonctionnalités sous forme de JSON', verbose_name='Fonctionnalités'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommandé'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_listings',
            field=models.IntegerField(default=5, help_text="Nombre maximum d'annonces. -1 pour illimité.", verbose_name="Nombre d'annonces max"),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Ex: Gratuit, Standard, Professionnel, Premium', max_length=50, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix mensuel en USD ou FCFA', max_digits=10, verbose_name='Prix'),
        ),
    ]
