# Generated by Django 6.0.6 on 2026-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DOMIORA', max_length=100)),
                ('tagline', models.CharField(default='Find. Rent. Own. Effortlessly.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='contact@domiora.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (212) 000-0001', max_length=30)),
                ('address', models.CharField(default='157 West 57th Street, New York, NY 10019', max_length=255)),
                ('opening_hours_weekdays', models.CharField(default='Lun - Ven: 9h - 18h', max_length=80)),
                ('opening_hours_weekend', models.CharField(default='Sam: 10h - 16h', max_length=80)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('smtp_host', models.CharField(blank=True, help_text='Configuré réellement via le fichier .env', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=120)),
                ('smtp_use_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
