# Generated by Django 5.2.15 on 2026-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_tiktok_sitesettings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Votre rêve, notre priorité', max_length=255),
        ),
    ]
