# Generated by Django 6.0.6 on 2026-06-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('location', 'Demande de location'), ('achat', "Demande d'achat"), ('visite', 'Demande de visite')], default='visite', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_requests', to='agents.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
