# Generated by Django 5.2.15 on 2026-07-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_video_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(choices=[('1_day', '1 jour'), ('3_days', '3 jours'), ('7_days', '7 jours'), ('14_days', '14 jours'), ('30_days', '30 jours')], max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField(help_text='Duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('boost_multiplier', models.PositiveSmallIntegerField(default=2, help_text='Visibility multiplier (2x, 3x, etc.)')),
                ('featured_placement', models.BooleanField(default=False, help_text='Show in featured section')),
                ('top_of_search', models.BooleanField(default=False, help_text='Show at top of search results')),
                ('badge_highlight', models.BooleanField(default=False, help_text='Add special badge')),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['duration_days', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PropertyBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('views_before_boost', models.PositiveIntegerField(default=0)),
                ('views_during_boost', models.PositiveIntegerField(default=0)),
                ('inquiries_before_boost', models.PositiveIntegerField(default=0)),
                ('inquiries_during_boost', models.PositiveIntegerField(default=0)),
                ('boost_score', models.PositiveIntegerField(default=0, help_text='Calculated boost score for ranking')),
                ('priority_level', models.PositiveSmallIntegerField(default=0, help_text='Priority level in search results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property_boost.boostpackage')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_daily_views_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('view_increase_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='property_boost.propertyboost')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyboost',
            index=models.Index(fields=['property', 'status'], name='property_bo_propert_340400_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyboost',
            index=models.Index(fields=['status', 'end_date'], name='property_bo_status_2cf9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyboost',
            index=models.Index(fields=['boost_score', 'priority_level'], name='property_bo_boost_s_c71345_idx'),
        ),
        migrations.AddIndex(
            model_name='boostanalytics',
            index=models.Index(fields=['boost', 'date'], name='property_bo_boost_i_705a55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boostanalytics',
            unique_together={('boost', 'date')},
        ),
    ]
