# Generated by Django 5.2.15 on 2026-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('demande', 'Nouvelle demande'), ('transaction', 'Transaction'), ('systeme', 'Système'), ('verification_approved', 'Validation identité'), ('verification_rejected', 'Refus identité')], default='info', max_length=30),
        ),
    ]
