# Generated by Django 5.2.15 on 2026-07-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_property_video_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('agent_signal_data', models.JSONField(blank=True, default=dict)),
                ('buyer_signal_data', models.JSONField(blank=True, default=dict)),
                ('screen_sharing_enabled', models.BooleanField(default=False)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Notes de la visite virtuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tours', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_tours', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tours', to='properties.property')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TourChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='virtual_tours.virtualtoursession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='virtualtoursession',
            index=models.Index(fields=['property', 'status'], name='virtual_tou_propert_588703_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualtoursession',
            index=models.Index(fields=['agent', 'scheduled_at'], name='virtual_tou_agent_i_4c6f13_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualtoursession',
            index=models.Index(fields=['buyer', 'scheduled_at'], name='virtual_tou_buyer_i_987d63_idx'),
        ),
        migrations.AddIndex(
            model_name='tourchatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='virtual_tou_session_667b91_idx'),
        ),
    ]
